// <auto-generated />
using System;
using Lince;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Lince.Migrations
{
    [DbContext(typeof(LinceContext))]
    [Migration("20251122131803_AttNotNull")]
    partial class AttNotNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("NivelAlerta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("OperadorId");

                    b.ToTable("LC_ALERTA", (string)null);
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Camera", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("LC_CAMERA", (string)null);
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.ToTable("LC_EQUIPE", (string)null);
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Operador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("LC_OPERADOR", (string)null);
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.ToTable("LC_SETOR", (string)null);
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Supervisor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<Guid?>("EquipeId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EquipeId");

                    b.ToTable("LC_SUPERVISOR", (string)null);
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Alerta", b =>
                {
                    b.HasOne("Lince.Infrastructure.Persistence.Entitites.Camera", "Camera")
                        .WithMany("Alertas")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lince.Infrastructure.Persistence.Entitites.Operador", "Operador")
                        .WithMany("Alertas")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Camera", b =>
                {
                    b.HasOne("Lince.Infrastructure.Persistence.Entitites.Setor", "Setor")
                        .WithMany("Cameras")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Operador", b =>
                {
                    b.HasOne("Lince.Infrastructure.Persistence.Entitites.Equipe", "Equipe")
                        .WithMany("Operadores")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Supervisor", b =>
                {
                    b.HasOne("Lince.Infrastructure.Persistence.Entitites.Equipe", "Equipe")
                        .WithMany("Supervisores")
                        .HasForeignKey("EquipeId");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Camera", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Equipe", b =>
                {
                    b.Navigation("Operadores");

                    b.Navigation("Supervisores");
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Operador", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("Lince.Infrastructure.Persistence.Entitites.Setor", b =>
                {
                    b.Navigation("Cameras");
                });
#pragma warning restore 612, 618
        }
    }
}
